### ISSUE TITLE
OpenStreetMap OAuth info about osm-revert

### ISSUE THREAD

**Issue by starsep** [Zaczero/osm-relatify#1]
I find it surprising that OAuth prompt is about [osm-revert](https://revert.monicz.dev/). I understand it was easier to share configuration between apps
![Screenshot_2023-06-03-09-49-12-88_d0ef7a9810af20f7b394f4f927b723b0](https://github.com/Zaczero/osm-relatify/assets/2798728/64038749-6faa-4b99-a68f-678580c13aea)

**Comment by Zaczero** [comment]
Fixed
