### ISSUE TITLE
Fails spliting roundabout and adapting **all** affected route relations

### ISSUE THREAD

**Issue by osm-ToniE** [Zaczero/osm-relatify#12]
I did a fix on a bus route and (according to Relatify) there was a need to split a roundabout into segments.

https://relatify.monicz.dev/?relation=9885680&load=1#map=19/47.756718/11.559851

Relatify failed fixing (removing unused segments, resorting segments) **all** affected other route relations - there are tons of them, this is a central roundabout used by many bus routes (load this into JOSM and you'll see how many).

BTW: many mappers consider having an un-split roundabout (single way) in route relations as a valid mapping habit.

Suggestion: do not split single-way roundabouts, that's a challenging task. iD and StreetComplete also fail on this and "create" broken route relations.

**Comment by Zaczero** [comment]
I see the issue, so after splitting the roundabout to many parts, some of them won't be used by other routes and must be removed from them. I think there will be easy fix for it. Let me focus on that now.

**Comment by Zaczero** [comment]
Fixed
