### ISSUE TITLE
`highway=service` cannot be selected

### ISSUE THREAD

**Issue by mcliquid** [Zaczero/osm-relatify#2]
I am editing a bus route which goes via a `highway=service` (parking aisle), but I cannot select this way. Are service roads filtered out?

**Comment by Zaczero** [comment]
The following service roads are excluded:

* driveway
* driveway2
* parking_aisle
* emergency_road

If a [parking_aisle](https://wiki.openstreetmap.org/wiki/Tag:service%3Dparking_aisle) road is commonly used by public transport traffic, it should also have an access tag, either `psv=designated` or `bus=designated`. Alternatively, you could consider changing the road type from parking aisle to just service.

The reason for this behavior is the wiki documentation:

> a subordinated way in a parking lot between rows of parking spaces that vehicles use to drive into and out of the spaces.

**Comment by Zaczero** [comment]
I think such feature would be quite complicated to implement, the way to go about this is to use Open-in-OSM buttons which are already present in Relatify, and then you would refresh the data with some other button (not yet implemented).

**Comment by osm-ToniE** [comment]
> Alternatively, you could consider changing the road type from parking aisle to just service.

+1 and the list should also include 'alley' not considering psv= or bus= at all

**Comment by Zaczero** [comment]
I added a rule for service=alley too. I think this issue can be closed now.
