### ISSUE TITLE
Feature Wish: Show bus stop ref more easily

### ISSUE THREAD

**Issue by JesseWeinstein** [Zaczero/osm-relatify#25]
Currently the `ref` value of a bus stop is only visible after clicking Inspect and waiting for OSM to load. I use that value to make sure I'm referring to the right stop, when there are multiple ones with similar names nearby. It would be nice if that value was visible in the menu that comes up when you right click on the stop (that currently just has the Inspect link) (or even added to the popup).

**Comment by Zaczero** [comment]
Could you please provide me with an example, Thanks :smiley: !

**Comment by JesseWeinstein** [comment]
Sure, here's an example of two stops with the same name:
![image](https://github.com/Zaczero/osm-relatify/assets/200568/dd44e522-b21e-4eab-a5d0-dea94c4d4b8a)

But they have different ref values ( The top, non-selected, one (https://www.openstreetmap.org/node/1399781241 ) has ref=42; while the other one (https://www.openstreetmap.org/node/1399781230 ) has ref=24). The request is to show the ref value in the interface, either just in the hover or the right-click menu.

**Comment by Dimitar5555** [comment]
`[ref] name` in the tooltip of the stop should do the job.

**Comment by mxxcon** [comment]
Alternatively, highlight the bus stop circle in a different color if its `ref=` tag matches the `ref=` tag of the line you are editing.
Doing that would make it easier to distinguish the correct stop if there's a bunch of them from different lines clustered nearby.

**Comment by Zaczero** [comment]
I will get back to those issues soon! Been busy with https://www.openstreetmap.org/user/NorthCrab/diary/401999 https://www.openstreetmap.org/user/NorthCrab/diary/402069 https://community.openstreetmap.org/t/openaedmap-a-map-of-automatic-external-defibrillators/100952/2 :hugs:

**Comment by JesseWeinstein** [comment]
> Alternatively, highlight the bus stop circle in a different color if its `ref=` tag matches the `ref=` tag of the line you are editing. Doing that would make it easier to distinguish the correct stop if there's a bunch of them from different lines clustered nearby.

The `ref=` value of a stop won't generally match the `ref=` of the route. The `network=` might match (if it's present), but that's a different issue.

No hurry on addressing these -- the tool as it stands is still very useful, and you are under no obligation to improve it further!

**Comment by mxxcon** [comment]
> The `ref=` value of a stop won't generally match the `ref=` of the route. The `network=` might match (if it's present), but that's a different issue.

Sorry, I meant `route_ref=` on a stop matching `ref=` of route.
`network=` is too generic. Every in front of a shopping center would have the same network tag but different routes

**Comment by JesseWeinstein** [comment]
Ah, yeah, `route_ref=` would work, if it's present. But I think it wouldn't be present in most cases, while `ref=` is a lot more likely.

**Comment by Zaczero** [comment]
![image](https://github.com/Zaczero/osm-relatify/assets/10835147/ee899d80-63c1-49dc-94f2-391479d06e37)
![image](https://github.com/Zaczero/osm-relatify/assets/10835147/ec3ba477-54ca-4581-af1b-5a2ddbf621e6)

Done

**Comment by JesseWeinstein** [comment]
Nice work! I've been meaning to thank you again for Relatify -- it's a great tool, and I wish it was better known.
