### ISSUE TITLE
Support public_transport=station 

### ISSUE THREAD

**Issue by JesseWeinstein** [Zaczero/osm-relatify#26]
It seems like only public_transport=platform can be selected, not public_transport=station. This makes it harder to include terminal stops.

**Comment by Zaczero** [comment]
I don't believe that's a valid case, and there may be some misunderstanding regarding the appropriate usage of this tag.

https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstation

> The public_transport=station tag is used to identify a railway station, a bus station or any other kind of a public transport station. It will almost certainly be part of a [public_transport](https://wiki.openstreetmap.org/wiki/Key:public_transport)=[stop_area](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstop_area) [relation](https://wiki.openstreetmap.org/wiki/Relation) which will contain a number of [public_transport](https://wiki.openstreetmap.org/wiki/Key:public_transport)=[platform](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dplatform)s, [public_transport](https://wiki.openstreetmap.org/wiki/Key:public_transport)=[stop_position](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstop_position)s and other elements.

Meaning, that a station should contain separately mapped platforms. It's simply a large collection, a "station".

I have read:
* https://wiki.openstreetmap.org/wiki/Public_transport
* https://wiki.openstreetmap.org/wiki/Tag:route%3Dbus
* https://wiki.openstreetmap.org/wiki/Buses
* https://wiki.openstreetmap.org/wiki/Proposal:Refined_Public_Transport

and none of them properly justify your use case but maybe I am missing something. Feel free to guide me in the right direction by providing me with tag documentation.

Perhaps @osm-ToniE could assist here, as you appear to have more experience in public transport knowledge.

**Comment by JesseWeinstein** [comment]
Ah, yeah, I think you are right. So it would be nice to have Relatify warn about this mis-tagging.

**Comment by osm-ToniE** [comment]
I agree.

There are only two objects which represent a stop:

- public_transport=platform - that's where the passengers wait (this can be node, way, area and some also use MP beside the way)
- public_transport=stop_position - that's where the vehicle stops (this can only be a node on the way)

That's all what is allowed for route relations.

In addition to that:

public_transport=station is usually a building (represented by a node, way, area), as known with trains

public_transport=stop_area is an MP grouping all platforms and stop_positions of a vehicle type. So there can be more then one for the same location: one for buses, one for trains, one for subway - each can be assigned a different name.
It can also include amenities like ticket vending machines, benches, ...

public_transport=stop_area_group then groups all such stop_area in a single MP

**Comment by osm-ToniE** [comment]
> Ah, yeah, I think you are right. So it would be nice to have Relatify warn about this mis-tagging.

Yep, PTNA does print an error message

**Comment by Zaczero** [comment]
Thank you @osm-ToniE :smiley:! This will help out a lot in future discussions, releases.

**Comment by Zaczero** [comment]
Performing validation on other objects is not currently planned for Relatify. The absence of a bus stop is a sufficient indication that something is wrong. :stuck_out_tongue:
