### ISSUE TITLE
Feature Wish: Correct mis-tagging of stop_position vs platform

### ISSUE THREAD

**Issue by JesseWeinstein** [Zaczero/osm-relatify#27]
Currently, (and correctly) both `public_transit=stop_position` and `public_transit=platform` show up, and are selectable. And stop_position is (correctly) checked that it is attached to a street included in the relation. However, if a stop_position isn't attached to *any* street, you just get a somewhat confusing error message. I think it should be possible for Relatify to give you the option of switching the mis-tagged stop to `public_transit=platform`, rather than requiring switching to another editor and spamming the Reload button till the fix shows up.

**Comment by Zaczero** [comment]
That's a good idea, but I won't be working on it for a specific reason:

I don't want to invest effort into supporting poor tagging, as that would create a never-ending loophole. Ideally, Relatify would have a tag editor (which I plan on adding for the relations themselves). However, enabling edits on all elements is a complex task. I believe this challenge has already been addressed by other editors (iD, JOSM). The reload feature is your friend here; I've designed it to preserve any changes you've made so far, without discarding them.

You can also click this button to quickly access the OSM view, from which you will be able to edit:
![image](https://github.com/Zaczero/osm-relatify/assets/10835147/14ec711b-8218-410b-a3c6-034cff982087)

An inspect in JOSM button is also on its way:
https://github.com/Zaczero/osm-relatify/pull/11

**Comment by Zaczero** [comment]
I want to keep the project simple, easy to maintain and improve. This feature would work against that goal.

**Comment by JesseWeinstein** [comment]
That makes sense to me. I think improving the error message might still be reasonable, but that's a smaller (and different) ask.
