### ISSUE TITLE
Start/stop markers do not show up automatically

### ISSUE THREAD

**Issue by mcliquid** [Zaczero/osm-relatify#3]
I have adjusted a bus relation, but I cannot save my changes or I cannot find the option to do so anywhere. Where should this button be?

![image](https://github.com/Zaczero/osm-relatify/assets/3351668/254fcbbe-616f-4919-aa9c-579a58af9924)

**Comment by mutipg** [comment]
You have to set Start line and End line (right mouse button on line):
![image](https://github.com/Zaczero/osm-relatify/assets/10333015/1b8feb7b-06da-4092-af32-1648e0e2fdc3)
![image](https://github.com/Zaczero/osm-relatify/assets/10333015/6b20a9d7-1b88-4fc2-bc7e-830563e9b848)
If your rote will be continuous, then it can be finished and send to OSM or download as osc.
![image](https://github.com/Zaczero/osm-relatify/assets/10333015/883e992f-0c67-446a-bb7b-8c4636836cb3)
