### ISSUE TITLE
Feature Wish: Show network if different networks are nearby

### ISSUE THREAD

**Issue by JesseWeinstein** [Zaczero/osm-relatify#33]
In some cases, there are two or more bus stops from different networks close to each other, sometimes with the same stop name. It would be helpful to show the network name in the tooltip in those cases.

**Comment by Zaczero** [comment]
Did the resolution of https://github.com/Zaczero/osm-relatify/issues/25 also happen to address this? Is there still any benefit to displaying the network?

**Comment by JesseWeinstein** [comment]
I think #25 did resolve this, since (hopefully) two different networks won't share stop numbers on stops near each other!
