### ISSUE TITLE
Remove unnecessary bolding of stop names with numbers in them

### ISSUE THREAD

**Issue by RCRalph** [Zaczero/osm-relatify#35]
Hello,

I've been using Relatify to add and update bus routes around Kraków, Poland and so far it's been really great.
While updating one of the bus routes I found out that when there are numbers in the stop name, Relatify will bold the numbers as if it was a stop number:

![image](https://github.com/Zaczero/osm-relatify/assets/36704328/c96bace3-1d61-4a80-a5be-c6d1bf198834)

I don't think that's necessary, the tool should bold just the stop number.

**Comment by Zaczero** [comment]
Resolved

![image](https://github.com/Zaczero/osm-relatify/assets/10835147/454a87e3-6b0e-4d10-a1a3-be9f850e9bd6)
