### ISSUE TITLE
Error 500 when trying to upload changes

### ISSUE THREAD

**Issue by mcliquid** [Zaczero/osm-relatify#4]
I've edited (extended) this relation: https://www.openstreetmap.org/relation/6228812
When I click on "Finish editing" and then on "Upload to OSM" there is a error 500:

![image](https://github.com/Zaczero/osm-relatify/assets/3351668/db3ddc17-19cf-49b3-a533-c04ad339d8f7)

EDIT: Download the osc file does not work too.

**Comment by Zaczero** [comment]
Fixed it, this has been caused by recent changes to the warning system, which made dacite to fail parsing.

**Comment by swaree** [comment]
hi, I know this was closed almost a year ago but now I'm facing the exact same issue with [this relation](https://www.openstreetmap.org/relation/17650239)

**Comment by Zaczero** [comment]
@swaree I'll check the logs tomorrow morning and let you know :-) TY!
