### ISSUE TITLE
Ignore oneway roads that can't be entered

### ISSUE THREAD

**Issue by Dimitar5555** [Zaczero/osm-relatify#40]
Currently OSM Relatify suggests to add roads that buses cannot enter because they are one-way. If these roads are not displayed, it would save a lot of time and clicks for the mappers.

![image](https://github.com/Zaczero/osm-relatify/assets/19364673/af99e648-b3ac-40e1-a599-17ef07ec2043)

**Comment by Zaczero** [comment]
I don't think it's a worthwhile feature. User should have a flexibility whether they want to draw a route from the start or from the end. This would add some complexity to the system too. But I can understand the benefit of making it a simpler user experience.

**Comment by Hidooo** [comment]
I think it's necessary to be able to add a route "backwards" until you can add new routes in relatify; otherwise you wouldn't be able to extend routes from the beginning.

**Comment by Zaczero** [comment]
This won't be worked on for now. Nonetheless, thank you for making the suggestion! 😊
