### ISSUE TITLE
Relatify can't handle conditional bus restrictions.

### ISSUE THREAD

**Issue by mxxcon** [Zaczero/osm-relatify#41]
Example relations 12381963 and 2632957.
They go over road segments which have the following real world restriction:
![image](https://github.com/Zaczero/osm-relatify/assets/847140/08bbf229-a89a-4de1-b088-4343bd5b6d60)
In OSM these segments are tagged as 
```
access=no
bus=no
bus:conditional=yes @ (operator=Metropolitan Transportation Authority)
emergency=designated
```
Unfortunately, relatify doesn't doesn't show such ways at all.
![image](https://github.com/Zaczero/osm-relatify/assets/847140/c6f3028a-88de-4086-b83e-6f7f79512d37)

**Comment by Zaczero** [comment]
Fixed in https://github.com/Zaczero/osm-relatify/commit/aac10271616f42dacd6f3c94c723088a2065f2a6
Thank you for reporting the issue!
