### ISSUE TITLE
Can't select specific bus stop

### ISSUE THREAD

**Issue by Dimitar5555** [Zaczero/osm-relatify#50]
Relation: https://www.openstreetmap.org/relation/16333620 
Stop: https://www.openstreetmap.org/node/11193541838

The stop refuses to show up for for some reason. It has the same tags as the other unnamed stops.

![image](https://github.com/Zaczero/osm-relatify/assets/19364673/a05324a3-1bf3-4bb5-97ff-69521f4f86fe)

**Comment by Zaczero** [comment]
Fixed, sending update to the server soon!
Thank you for reporting.
