### ISSUE TITLE
bus direction is animated incorrectly

### ISSUE THREAD

**Issue by Mhowser** [Zaczero/osm-relatify#53]
https://relatify.monicz.dev/#map=18/39.088362/-122.791969
https://www.openstreetmap.org/relation/16467852
![image](https://github.com/Zaczero/osm-relatify/assets/24195572/ef712d4b-239f-4e6d-97e6-0319be3fe253)
Blue arrows are the correct route animation, Red is incorrect.

The bus direction for this relation is West -> East, but this small section does not match up with that. I checked that I added the route correctly in JOSM.

**Comment by Dimitar5555** [comment]
The red arrows seem correct since buses in RHD countries have doors on their right side. Otherwise I can't see how the bus would reach the stop if the red arrows were reversed.

**Comment by Zaczero** [comment]
It's possible that it's a mapping issue then. As correctly pointed out, the algorithm seems to have a strong preference for routes that include a platform on the right-hand side.

**Comment by Mhowser** [comment]
You might be correct, this is my first time mapping a bus route so I will recheck that stop later today.
