### ISSUE TITLE
OSMI shows relation as being valid, Relatify complains about it not being valid

### ISSUE THREAD

**Issue by habi** [Zaczero/osm-relatify#57]
https://www.openstreetmap.org/relation/10394510 is shown as valid by [Geofabriks OSM Inspector](https://tools.geofabrik.de/osmi/?view=pubtrans_routes&lon=7.44366&lat=46.94767&zoom=15&baselayer=Geofabrik%20Standard&overlays=ptv2_routes_valid%2Cptv2_routes_invalid%2Cptv2_error_ways%2Cptv2_error_nodes), but Relatify complains that the "Relation must be a PTv2 bus route".

I would like to fix the error, but don't know how.
It would be great if Relatify can give some pointers on how to make the route valid.

**Comment by mutipg** [comment]
Your relation is `route=trolleybus`, but relatify only works with `route=bus` and this causes an error.

**Comment by habi** [comment]
OK, that's not clear from the error message.
Also, this issue is a duplicate of https://github.com/Zaczero/osm-relatify/issues/7, thus closing it.
