### ISSUE TITLE
Hint: if splitting roundabouts ...

### ISSUE THREAD

**Issue by osm-ToniE** [Zaczero/osm-relatify#6]
I get an error message if a roundabout is not split and completely included in a relation.
One can argue pro/con related to this. PTNA has an analysis option allowing this.

**But**: if Relatify splits the roundabout when clicking on the superfluous ways: take care that other route relations are not damaged and must be manipulated in the same way. This is a challenging task, iD often fails here.

If a roundabout is split into segments, only used segments must be in a relation.

**Comment by Zaczero** [comment]
There is an automatic splitting system for roundabouts which consist of just 1 way. It is split at each intersection. The Relatify app [already handles](https://github.com/Zaczero/osm-relatify/blob/40046e0b75f4784bccb4751becde5fa817c36e94/web/relation_builder.py#L232) updating of other relations. Let me know if I misunderstood your question.

**Comment by osm-ToniE** [comment]
>     for way_id in split_ways:
>       way = id_way_map[native_id_element_ids_map[way_id][1]]
> 
>         # iterate over each related relation
>         for relation in parents.id_relations_map[way_id]:
>             relation_id = int(relation['@id'])

I think this will do the magic for the parents downloaded.
Thanks
