### ISSUE TITLE
Internal Server Error when uploading changes

### ISSUE THREAD

**Issue by Zaczero** [Zaczero/osm-relatify#70]
hi, I know this was closed almost a year ago but now I'm facing the exact same issue with [this relation](https://www.openstreetmap.org/relation/17650239)

_Originally posted by @swaree in https://github.com/Zaczero/osm-relatify/issues/4#issuecomment-2137990046_

**Comment by Zaczero** [comment]
The below assertion fails which indicates that route.members or route.extraWaysToUpdate are incomplete.

```py
    for group in native_id_element_ids_map.values():
        assert (
            len(group) == split_element_id(group[1]).max_num
        ), f'Split ways are not complete: {", ".join(f"{k}={v}" for k, v in group.items())}'
```

**Comment by Zaczero** [comment]
@swaree could you please send a screenshot of the route, when the issue occurs?

**Comment by swaree** [comment]
sure thing
![tmp_ac02e3ab-f570-4c26-bbdf-6726ce2b6292](https://github.com/Zaczero/osm-relatify/assets/13753165/5fab21ee-0a4f-44cc-95c1-533ece54314a)

**Comment by swaree** [comment]
nice, it did work now, thank you! I removed parts of the roundabout in both inbound and outbound buses. thanks again for the very useful tool.
