### ISSUE TITLE
Relatify picks up subway stations for tram routes

### ISSUE THREAD

**Issue by Dimitar5555** [Zaczero/osm-relatify#79]
relation/12684731

Relatify is picking up subway stopping positions when working with tram routes. Maybe it should be looking for `tram=yes` in https://github.com/Zaczero/osm-relatify/blob/main/web/overpass.py#L103-L108?

NDK 1 subway station (picked up by Relatify)
https://www.openstreetmap.org/node/1905045720
https://www.openstreetmap.org/node/7669742831
Serdika 2 subway station (picked up by Relatify)
https://www.openstreetmap.org/node/7962122129
https://www.openstreetmap.org/node/7962122128
Lions' Bridge subway station (not picked up, possibly because of the lack of platforms)
https://www.openstreetmap.org/node/753015314
https://www.openstreetmap.org/node/11583691559

**Comment by Zaczero** [comment]
Hey I pushed an update, let me know if it's fine now :slightly_smiling_face: !

**Comment by Dimitar5555** [comment]
It's working as expected now, no subway stations. Thank you!
