### ISSUE TITLE
Update failed - 412

### ISSUE THREAD

**Issue by adamos466** [Zaczero/osm-relatify#88]
Is it a bug in Relatify, or in OSM?
![412](https://github.com/user-attachments/assets/b3956458-127a-425e-8844-5a790e2eab73)

**Comment by mutipg** [comment]
It looks like bug. These ways was deleted yesterday (2024-11-27T18:58:20Z), but Realtify still is looking for them before upload. I attached .osm file generated from Relatify before upload. Buggy ways are in lines 327, 328:
```
<member type="way" ref="976729464" role=""></member>
<member type="way" ref="976729463" role=""></member>
```
[relatify_4524123_2024-11-28T21_55_32.108Z.zip](https://github.com/user-attachments/files/17952555/relatify_4524123_2024-11-28T21_55_32.108Z.zip)

**Comment by Dimitar5555** [comment]
Maybe the overpass instance can't keep up with the minutely updates?

**Comment by adamos466** [comment]
Maybe, I am not an expert in that. How to mitigate such issue? Larger intervals between edits? 5 minutes? Or more?

**Comment by Dimitar5555** [comment]
We can't do much. @Zaczero can look into it and probably restart the server / do a data reimport (assuming that the problem is indeed in the overpass instance).

**Comment by Zaczero** [comment]
Hey, about a week ago my server had DNS issues that caused my Overpass instance to stop updating. A few days ago I have resolved the issue and Overpass is up-to-date again. Please let me know if that works and sorry for the delay!

**Comment by adamos466** [comment]
Yes, I see no issues for last two days. Thanks for the quick fix!
