### ISSUE TITLE
Add a "show" button to the error "Some stops are not reached"

### ISSUE THREAD

**Issue by mcliquid** [Zaczero/osm-relatify#9]
It would be nice if you could implement a button to zoom to the stops which are not reached to fix the problem faster :) 

![image](https://github.com/Zaczero/osm-relatify/assets/3351668/bbabaced-b46b-480f-a1de-6539413357a8)

**Comment by JesseWeinstein** [comment]
Or at least a count of how many.

**Comment by Zaczero** [comment]
> Or at least a count of how many.

I will do the button

**Comment by Zaczero** [comment]
![image](https://github.com/Zaczero/osm-relatify/assets/10835147/9fa5a5a0-5147-42cc-b21d-78ca56b352c0)
