### ISSUE TITLE
Why is this tool splitting ways at every junction?

### ISSUE THREAD

**Issue by DaveF63** [Zaczero/osm-relatify#90]
https://www.openstreetmap.org/way/1346459768

https://www.openstreetmap.org/changeset/160654778#map=14/51.37895/-2.35053

**Comment by Zaczero** [comment]
Hey, the split occurs at every junction of a way whenever at least one split must be performed on that way. Why? For simplicity. There are no rules in OSM that define when a way should be split and when not. Splitting at junctions sounds like a reasonable behavior. From my OSM experience, it's a matter of time when a way will have to be split on a junction: be it from difference in lanes/maxspeed/surface/highway, turn restrictions etc. It's a common scenario.

**Comment by DaveF63** [comment]
That is just utter rubbish.

Your program does not require ways to be split at every junction.
No program require that.

There is no mention of this practise in the wiki.

That it is required under specific circumstances it doesn't mean it has to be performed everywhere.

Splitting ways unnecessarily increases future editing time.

Entropy is the lack of order or predictability; gradual decline into disorder, not "simplicity"

You need to fix this poor example of programming.

**Comment by Zaczero** [comment]
I won't continue this discussion with someone who has such an attitude.
